[package]
  cjc-version = "1.0.1"
  name = "cangstream"
  description = "CangStream Web Framework v1.2 - AI Agent Ready"
  version = "1.2.0"
  src-dir = "src"
  output-type = "executable"

  [target.x86_64-w64-mingw32]
  [target.x86_64-w64-mingw32.bin-dependencies]
  path-option = ["D:\\cangjie-stdx-windows-x64-1.0.1.1\\windows_x86_64_llvm\\dynamic\\stdx"]

  [target.x86_64-unknown-linux-gnu]
  [target.x86_64-unknown-linux-gnu.bin-dependencies]
  path-option = ["/opt/cangjie/cangjie-stdx/linux_x86_64_llvm/dynamic/stdx"]

[dependencies]
